/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, MeshWobbleMaterial } from '@react-three/drei'

export default function Tab(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/githubtab-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.56, -0.05, 0.03]} rotation={[Math.PI / 2, 0, -1.55]} scale={28.36}>
        <mesh geometry={nodes.Curve021.geometry} material={materials['glossy putih']} />
        <mesh geometry={nodes.Curve021_1.geometry} material={materials.github} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[0.02, -0.02, -0.06]} />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[-0.99, 0, -0.05]}
        rotation={[0, 0, -1.58]}
        scale={[1.18, 1.18, 1.18]}
        
      />
    </group>
  )
}

useGLTF.preload('/githubtab-transformed.glb')
