/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GrandExchange(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/osrsGE.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-28.09, 0, 37.77]}>
        <mesh geometry={nodes.Mesh_0001.geometry} material={materials['rs_untextured.001']} />
        <mesh geometry={nodes.Mesh_1001.geometry} material={materials['rs_texture_8.001']} />
        <mesh geometry={nodes.Mesh_2001.geometry} material={materials['rs_texture_11.001']} />
        <mesh geometry={nodes.Mesh_3001.geometry} material={materials['rs_texture_60.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/osrsGE.glb')
